[package]
name = "birthday_bot"
version = "1.0.0"

[addresses]
std = "0x1"
overmind = "0x1337"

[dependencies]
# orig rev "093b497d1267715a222845aad4fd3ca59da90e8d"
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "aptos-cli-v2.0.0" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-cli-v2.0.0" }